spring:
  application:
    name: carrive-auth
  mail:
    host: smtp.gmail.com
    port: 587
    username: stevekamga18@gmail.com
    password: okfh dywd wvlf cyny
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        transport:
          protocol: smtp
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: carrive_db
      host: localhost
      port: 27017
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
  instance:
    ip-address: "localhost"
